# Azure DevOps pipeline for Azure deployment

variables:
  group: test
  service_connection: 'sc-terraform3'

trigger:
  branches:
    include:
    - main
 
pool:
  vmImage: ubuntu-latest

stages:
- stage: use_cli_to_deploy_aks
  displayName: use cli to deploy aks
  jobs:
  - job: deploy_aks
    steps:
    - task: HelmInstaller@0
      inputs:
       helmVersion: '2.14.1'
       installKubectl: true
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'sc-terraform3'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 
         'az aks get-credentials --name aks-stc -g rg-aks-stcs-coreservices'
        