# Azure DevOps pipeline for Azure deployment

variables:
  group: test
  service_connection: 'sc-terraform3'

trigger:
  branches:
    include:
    - main
 
pool:
  vmImage: ubuntu-latest

stages:
- stage: use_cli_to_deploy_aks
  displayName: use cli to deploy aks
  jobs:
  - job: deploy_aks
    steps:
    - task: HelmInstaller@0
      inputs:
       helmVersion: '2.14.1'
       installKubectl: true
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'sc-azurearm'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 
         'az aks get-credentials --name aks-stcs -g rg-aks-stcs-coreservices'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'sc-aks-stcs'
        command: 
        useConfigurationFile: true
        configurationType: 'inline'
        inline: 'kubectl get pod -A'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        
    - task: Docker@2
      inputs:
        containerRegistry: 'sc-acr-stcs-basic'
        repository: 'nginx'
        command: 'push'
        arguments: 'mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine'