# Azure DevOps pipeline for Azure deployment

variables:
  group: test
  service_connection: 'sc-terraform3'

trigger:
  - main
 
pool:
  vmImage: ubuntu-latest

stages:
- stage: use_cli_to_deploy_aks
  displayName: use cli to deploy aks
  jobs:
  - job: deploy_aks
    steps:
    - task: HelmInstaller@0
      inputs:
       helmVersion: '2.14.1'
       installKubectl: true
    - task: helm@1
      inputs:
        subCommand: 'repo'
        arguments: 'add bitnami https://charts.bitnami.com/bitnami'
    - task: helm@1
      inputs:
        subCommand: 'install'
        arguments: 'nginx bitnami/nginx'
      
    # - task: AzureCLI@2
    #   inputs:
    #     azureSubscription: 'sc-azurearm'
    #     scriptType: 'bash'
    #     scriptLocation: 'inlineScript'
    #     inlineScript: 
    #      'az acr import --name sc-acr-stcs-basic --source quay.io/strimzi/kafka:0.31.1-kafka-3.2.3 --image strimzi/kafka:0.31.1-kafka-3.2.3'

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'sc-aks-serviceaccount'
        useConfigurationFile: true
        configurationType: 'inline'
        inline: 
         kubectl get service
         kubectl get sa
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        arguments: 

      
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'sc-aks-serviceaccount'
        namespace: 'default'
        manifests: 
          'service-debezium-connect.yml'

    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'sc-acr-stcs-basic'
    #     repository: 'nginx'
    #     command: 'push'
    #     arguments: 'mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine'