# Azure DevOps pipeline for Azure deployment

#variables:
#- group: terraform-tuesdays

trigger:
  branches:
    include:
    - main
  # paths:
  #  include:
  # - 2021-05-11-ADO/vnet

stages:
- stage: Validate
  displayName: Validate
  jobs:
  - job: validate
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

  # Init
    - task: TerraformTaskV3@3
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'sc-terraform'
        backendAzureRmResourceGroupName: 'rg-terraform'
        backendAzureRmStorageAccountName: 'stterraform2022'
        backendAzureRmContainerName: 'stcontainerterraform'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTaskV3@3
      inputs:
        provider: 'azurerm'
        command: 'plan'



