apiVersion: v1
kind: Service
metadata:
  name: service-mllp-http
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
 S # loadBalancerIP: 100.67.68.197
  ports:
  - port: 2575
  selector:
    app: mllp-http