apiVersion: v1
kind: Service
metadata:
  name: service-debezium-connect
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.67.64.10
  ports:
  - port: 2575
  selector:
    app: debezium-connect