apiVersion: v1
kind: Service
metadata:
  name: service-mllp-http
  namespace: ns-mllp-http-dev
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  # loadBalancerIP: 100.67.64.200
  ports:
  - port: 2575
  selector:
    app: mllp-http